### ISSUE TITLE
error after installing

### ISSUE THREAD

**Issue by vyrus001** [keystone-engine/keypatch#17]
immediately after install on v6.95.160808 I get the following err on startup.

```
keypatch.py: name 'KS_ARCH_X86' is not defined
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA 6.95\python\ida_idaapi.py", line 509, in IDAPython_ExecScript execfile(script, g)
  File "C:/Program Files (x86)/IDA 6.95/plugins/keypatch.py", line 111, in <module> class Keypatch_Asm:
  File "C:/Program Files (x86)/IDA 6.95/plugins/keypatch.py", line 114, in Keypatch_Asm
"X86 16-bit": (KS_ARCH_X86, KS_MODE_16),                # X86 16-bit NameError: name 'KS_ARCH_X86' is not defined
```

**Comment by aquynh** [comment]
can you follow the instructions at https://github.com/keystone-engine/keystone/issues/243, and report back the result?

**Comment by vyrus001** [comment]
thank you, simply installing keystone via the installer shown in that issue made it work. Apparently the supporting lib was simply not installed

**Comment by aquynh** [comment]
glad to hear it works for you. if you are happy, dont forget to star our Keypatch & Keystone repos :-)
