### ISSUE TITLE
Installation Issue: "ImportError: cannot import name arm_const"

### ISSUE THREAD

**Issue by cxm95** [keystone-engine/keypatch#40]
Hi,

I want to install keystone on my Mac 10.12.6, IDA Pro 7.0;

After following the instructions [https://github.com/keystone-engine/keypatch/issues/28](url), I installed all required `python` and `dylib`. And keystone can be import from my own `/usr/bin/python.`

However, I got an `ImportError: cannot import name arm_const` when `import keystone` in the console of ida and don't know why.

I wasted several hours on searching the solution but nothing worked.

Any suggestions?

Thanks!

**Comment by cxm95** [comment]
## Details:

![image](https://user-images.githubusercontent.com/8190982/39353533-91a6b936-4a3a-11e8-86d2-afb163c76b06.png)

```
Python>import os
Python>os.sys.path
['/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/lib/python2.7/lib-dynload', '/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/lib/python2.7/lib-dynload/ida_64', '/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python', **'/Users/cxm/Library/Python/2.7/lib/python/site-packages'(in which keystone lies in)**, '/Library/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python', '/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins']
```

```
Python>import keystone
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/cxm/Library/Python/2.7/lib/python/site-packages/keystone/__init__.py", line 2, in <module>
    from . import arm_const, arm64_const, mips_const, sparc_const, hexagon_const, systemz_const, ppc_const, x86_const
ImportError: cannot import name arm_const
```

**Comment by fjh658** [comment]
Your problem cannot be reproduced.

Quickly use, portability, you can

```
cp -r "~/Library/Python/2.7/lib/python/site-packages/keystone"  "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/lib/python2.7/lib-dynload"
```

**Comment by ftk-sostupid** [comment]
I got same problem in Kali. I'm using keystone-engine for gef.
![1l d6n6 sx4bxpgmyofi47f](https://user-images.githubusercontent.com/30171892/45739359-60e17400-bc25-11e8-85a9-39992401074c.png)

It's very confusing.
