### ISSUE TITLE
Error in Ida Pro 7.0

### ISSUE THREAD

**Issue by ghost** [keystone-engine/keypatch#52]
D:\IDA 7.0\plugins\keypatch.py: cannot import name arm_const
Traceback (most recent call last):
  File "D:\IDA 7.0\python\ida_idaapi.py", line 553, in IDAPython_ExecScript
    execfile(script, g)
  File "D:\IDA 7.0\plugins\keypatch.py", line 23, in <module>
    from keystone import *
  File "C:\Python27\lib\site-packages\keystone\__init__.py", line 2, in <module>
    from . import arm_const, arm64_const, mips_const, sparc_const, hexagon_const, systemz_const, ppc_const, x86_const
ImportError: cannot import name arm_const

**Comment by DavidNorena** [comment]
any luck ?

**Comment by aquynh** [comment]
this is probably because Keystone is not properly setup.
you can install newer version of Keystone now, with:

```
pip install keystone-engine --pre
```

and hopefully the problem is solved.
