### ISSUE TITLE
IDA7.0 on Win10

### ISSUE THREAD

**Issue by rialbat** [keystone-engine/keypatch#70]
I followed all the installation steps, but I received these errors:

C:\Program Files\IDA 7.0\plugins\keypatch.py: No module named six
Traceback (most recent call last):
  File "C:\Program Files\IDA 7.0\python\ida_idaapi.py", line 553, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Program Files/IDA 7.0/plugins/keypatch.py", line 56, in <module>
    import six
ImportError: No module named six

**Comment by rialbat** [comment]
Fixed: just install six)

**Comment by Revester** [comment]
"just"? How?
