### ISSUE TITLE
IDA 7.5 Issue

### ISSUE THREAD

**Issue by mnemonic-re** [keystone-engine/keypatch#76]
Installed newest Keypatch but getting:

keypatch.py: name 'KS_ARCH_X86' is not defined
Traceback (most recent call last):
  File "\python\3\ida_idaapi.py", line 615, in IDAPython_ExecScript
    exec(code, g)
  File "/plugins/keypatch.py", line 265, in <module>
    class Keypatch_Asm:
  File "/plugins/keypatch.py", line 268, in Keypatch_Asm
    "X86 16-bit": (KS_ARCH_X86, KS_MODE_16),                # X86 16-bit
NameError: name 'KS_ARCH_X86' is not defined

Tried everything but it won't go away.

**Comment by mnemonic-re** [comment]
Solved the problem. Made a new Windows installation and installed the wrong python version.
