### ISSUE TITLE
da_idaapi.py", line 616, in IDAPython_ExecScript exec(code, g)

### ISSUE THREAD

**Issue by Fallen1997** [keystone-engine/keypatch#81]
**E:\Hex\plugins\keypatch.py: module 'idaapi' has no attribute 'Choose2'
Traceback (most recent call last):
File "E:\Hex\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
exec(code, g)
File "E:/Hex/plugins/keypatch.py", line 1134, in
class SearchResultChooser(idaapi.Choose2):
AttributeError: module 'idaapi' has no attribute 'Choose2'**

I'm using the lastest release 2.1 from github. i've been looking for solution and trying to solve this for hours

**Comment by Fallen1997** [comment]
I  got it working.

I'm using ida 7.5 SP3 on windows. 
if your IDA giving similar error, i did this then it worked.


1. Open CMD (command prompr) as ADMINISTRATOR
2. Type cd C:\Program Files\IDA Pro 7.5 SP3             ( or cd then wherever you have IDA path installed to)
3.  Type idapyswitch.exe   (This comes with IDA 7.5+ this allows you to switch to python 3)
4.  You will be able to pick a number, in my case 0 was python 3. after that it should say "Applying version" or something similar, if the console closes right away that means you did not open cmd as admin
5. now Open cmd as admin again, type pip install six. skip if you done this  already
6. Type in CMD pip install keystone-engine
7. Download Keypatch from  [HERE](https://github.com/keystone-engine/keypatch/blob/08e743b841be90c99554b7fa4a6f5e11c6b1d8f8/keypatch.py)
8. Copy the keypatch.py and go to the IDA installation folder then go to plugin, paste it there.

**Comment by Golbeze** [comment]
i encounter a same situation, and and i found it was the porting problem in keypatch code, so i patch the source, and finally reach a place that many code call idaapi.add_menu_item,which is already deprecated in new version, it took much time to write new code suit for 7.5, as IDA introduce a more flexible mechanism to performance menu item,so i came here to find something simple to fix it up

**Comment by Golbeze** [comment]
also working for me, amazing

**Comment by leileigong** [comment]
also working for me, thanks

**Comment by heokute** [comment]
working for me, thanks a lot :)

**Comment by OrinSan** [comment]
update you keypatch.py from 
https://github.com/keystone-engine/keypatch/blob/08e743b841be90c99554b7fa4a6f5e11c6b1d8f8/keypatch.py
